//
// Generated file, do not edit! Created by opp_msgc 4.5 from linklayer/ieee8021d/common/Ieee8021dBPDU.msg.
//

#ifndef _IEEE8021DBPDU_M_H_
#define _IEEE8021DBPDU_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif

// cplusplus {{
#include "MACAddress.h"
// }}



/**
 * Class generated from <tt>linklayer/ieee8021d/common/Ieee8021dBPDU.msg</tt> by opp_msgc.
 * <pre>
 * packet BPDU
 * {
 *     unsigned int protocolIdentifier;          
 *     unsigned int protocolVersionIdentifier;   
 * 
 *     unsigned int bpduType;                    
 *     bool tcaFlag;                             
 *     bool tcFlag;                              
 * 
 *     MACAddress rootAddress;                   
 *     unsigned int rootPriority;                
 *     unsigned int rootPathCost;                
 * 
 *     MACAddress bridgeAddress;                 
 *     unsigned int bridgePriority;              
 * 
 *     unsigned int portNum;                     
 *     unsigned int portPriority;                
 * 
 *     simtime_t messageAge;                     
 *     simtime_t maxAge;                         
 *     simtime_t helloTime;                      
 *     simtime_t forwardDelay;                   
 * }
 * </pre>
 */
class INET_API BPDU : public ::cPacket
{
  protected:
    unsigned int protocolIdentifier_var;
    unsigned int protocolVersionIdentifier_var;
    unsigned int bpduType_var;
    bool tcaFlag_var;
    bool tcFlag_var;
    MACAddress rootAddress_var;
    unsigned int rootPriority_var;
    unsigned int rootPathCost_var;
    MACAddress bridgeAddress_var;
    unsigned int bridgePriority_var;
    unsigned int portNum_var;
    unsigned int portPriority_var;
    simtime_t messageAge_var;
    simtime_t maxAge_var;
    simtime_t helloTime_var;
    simtime_t forwardDelay_var;

  private:
    void copy(const BPDU& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BPDU&);

  public:
    BPDU(const char *name=NULL, int kind=0);
    BPDU(const BPDU& other);
    virtual ~BPDU();
    BPDU& operator=(const BPDU& other);
    virtual BPDU *dup() const {return new BPDU(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getProtocolIdentifier() const;
    virtual void setProtocolIdentifier(unsigned int protocolIdentifier);
    virtual unsigned int getProtocolVersionIdentifier() const;
    virtual void setProtocolVersionIdentifier(unsigned int protocolVersionIdentifier);
    virtual unsigned int getBpduType() const;
    virtual void setBpduType(unsigned int bpduType);
    virtual bool getTcaFlag() const;
    virtual void setTcaFlag(bool tcaFlag);
    virtual bool getTcFlag() const;
    virtual void setTcFlag(bool tcFlag);
    virtual MACAddress& getRootAddress();
    virtual const MACAddress& getRootAddress() const {return const_cast<BPDU*>(this)->getRootAddress();}
    virtual void setRootAddress(const MACAddress& rootAddress);
    virtual unsigned int getRootPriority() const;
    virtual void setRootPriority(unsigned int rootPriority);
    virtual unsigned int getRootPathCost() const;
    virtual void setRootPathCost(unsigned int rootPathCost);
    virtual MACAddress& getBridgeAddress();
    virtual const MACAddress& getBridgeAddress() const {return const_cast<BPDU*>(this)->getBridgeAddress();}
    virtual void setBridgeAddress(const MACAddress& bridgeAddress);
    virtual unsigned int getBridgePriority() const;
    virtual void setBridgePriority(unsigned int bridgePriority);
    virtual unsigned int getPortNum() const;
    virtual void setPortNum(unsigned int portNum);
    virtual unsigned int getPortPriority() const;
    virtual void setPortPriority(unsigned int portPriority);
    virtual simtime_t getMessageAge() const;
    virtual void setMessageAge(simtime_t messageAge);
    virtual simtime_t getMaxAge() const;
    virtual void setMaxAge(simtime_t maxAge);
    virtual simtime_t getHelloTime() const;
    virtual void setHelloTime(simtime_t helloTime);
    virtual simtime_t getForwardDelay() const;
    virtual void setForwardDelay(simtime_t forwardDelay);
};

inline void doPacking(cCommBuffer *b, BPDU& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, BPDU& obj) {obj.parsimUnpack(b);}


#endif // _IEEE8021DBPDU_M_H_
